### PR TITLE
Delete User

### LINKED ISSUE #86: Delete User

### PR DESCRIPTION
**Pull request by MaraJade**
Fixes #86 
## Changes in this PR.

- [X] Added delete user page
## Testing this PR.

1. Run `nosetests`
2. Log in as site admin
3. Create a user, then delete it
### Expected Output.

```
$ nosetests
............................................................................
----------------------------------------------------------------------
Ran 76 tests in 1.257s

OK
```

@osuosl/devs

### CODE REVIEW

**Comment by aaroncohen73** [comment]
+1

**Comment by mathuin** [comment]
Tests passed, rebuilt Docker container, started server.

Created user named `deleteme`.  Clicked on list user page.  User not displayed.  Typed `deleteme` into username field.  User was displayed -- but with different Display name and email than I had specified.  Clicked `DELETE`, got two buttons -- `Yes, delete this user` and `No`.  Chose yes, got users page with `Deletion successful`.  Searched again for `deleteme`, found it.

I had the same results when trying to create and delete activities.  Is it something I am doing?

**Comment by Kennric** [comment]
I am not seeing what @mathuin saw, this works correctly for me. Can we get another attempt to replicate? @MaraJade

**Comment by MaraJade** [comment]
I can't replicate it either. Creating, viewing, and deleting the user all work the way they're supposed to for me.

**Comment by aaroncohen73** [comment]
@Kennric @MaraJade Mathuin was having issues because he was running the app with TESTING set to True in config.py. It's not related to this PR.

**Comment by leian7** [comment]
When I create a user and try to delete from the users page, I get the page with the buttons. When I click "yes, delete" I get "UUID not found", and from the users page I can see that my user wasn't deleted. When I go directly to /users/delete, I get "Username not found." My TESTING is set to False and I've rebuilt my container.

**Comment by leian7** [comment]
Cool, I can delete users from the users page now, although when I follow the /users/delete link directly, I still get "Username not found." Is this normal/not covered by this PR?

**Comment by MaraJade** [comment]
That's how it's supposed to work. If you don't give it a username in the url, you can't delete a user.

**Comment by leian7** [comment]
+1

**Comment by Kennric** [comment]
+1

**Pull request merged**
