### PR TITLE
Add pull request template to timesync-frontend-flask

### PR DESCRIPTION
**Pull request by matthewrsj**
We have been using a pull request template in IAM for a while now (thanks @ElijahCaine for introducing that). I was skeptical at first but it is extremely helpful, especially for including the steps necessary to test the PR. As a reviewer who isn't actively working on the codebase, I would love to see this.

@subnomo @aaroncohen73 @Kennric

### CODE REVIEW

**Comment by pop** [comment]
@matthewrsj Add an 'expected output' section.

**Comment by aaroncohen73** [comment]
+1

**Comment by subnomo** [comment]
+1

**Comment by ElijahCaine** [comment]
Ship it!

**Pull request merged**
