### PR TITLE
Edit times page

### PR DESCRIPTION
**Pull request by aaroncohen73**
fixes issue #31 
## Changes in this PR.

- [X] Added page to edit the attributes of a time entry
- [X] Links added to report page so users can edit their own times
## Testing this PR.

1. Run `flake` and `nosetests`
2. Log in as a user that has submitted a time
3. Navigate to /times and click the link to the side of that user's time
4. Edit the time and submit the update
5. See that the time has been updated
### Expected Output.

After the time has been updated, the updates should be immediately visible on the /times page.

@osuosl/devs

### CODE REVIEW

**Comment by Kennric** [comment]
Looks good to me so far +1 when tested against staging

**Comment by aaroncohen73** [comment]
~~This PR is currently blocked until a new version of Pymesync is released that includes [this fix](https://github.com/osuosl/pymesync/issues/145)~~

EDIT: Unblocked!

**Comment by Kennric** [comment]
+1

**Comment by pop** [comment]
@aaroncohen73 
Despite the test passing I have some problems with this PR.
1. When I try to edit a time as the admin I get a permission denied. Is that supposed to be the case? I was under the impression that admins can edit all times. This theory is supported by the 'EDIT' link being next to _all_ times on the `/times` endpoint, but when I click that link sends me to a `Permission Denied` page.
2. ~~Editing times does not actually update them. When I logged in as a test user and updated one of those user's times it did not actually change the time. The time just shows up as `0h0m` in the view page and on the edit-time form.~~

EDIT: I was doing a few things wrong:
- TESTING was not set in my config.py, so was implicitly True? Either way I was getting test data.
- My url was not set properly. It was missing the /v0/ at the end.

The first point still stands. As `admin` I was only able to edit admin's times.

**Comment by pop** [comment]
I was able to get this to work once. There are a few problems on our timesync-node staging server so there were a lot of `internal server error`s but I think I can say this is good go to. +1 from me.

**Pull request merged**
