### PR TITLE
Use cached project and activity data for create/edit/view times

### LINKED ISSUE #126: Better utilize cached data
We currently have data (such as user projects) stored in the session, and we should make better use of that data. For example, `session['projects']` can be used as project choices on the create_time form instead of having to make an API call. When #119 is merged in, we can use that data for things like selecting activities.

### PR DESCRIPTION
**Pull request by aaroncohen73**
Fixes #126 
## Changes in this PR.

- [X] Cached projects and activities are used on create/edit/view time pages
## Testing this PR.

1. Run `nosetests`
2. Make sure that `TIMESYNC_URL` is set to `http://timesync-staging.osuosl.org/v0` in config.py
3. Run the app and log in as `admin`/`timesync-staging`
4. Go to `/times/create` and see that `activities` is now a multiselect box
5. Go to `/times` and see that `projects` and `activities` are both multiselect boxes
### Expected Output.

```
14:30 $ nosetests
................................................................................................................................
----------------------------------------------------------------------
Ran 128 tests in 10.569s

OK
```

@osuosl/devs

### CODE REVIEW

**Comment by subnomo** [comment]
Definitely going to need CSS later to improve usability, but it does what it should. :+1:

**Comment by pop** [comment]
lgtm +1 good work, this is really nice.

Is there a reason we're not making users a multi-iselect box too?

**Comment by aaroncohen73** [comment]
@ElijahCaine I don't think there was a reason not to do that. I've added it in just now, so could you quickly look it over before it gets merged?

**Comment by pop** [comment]
@aaroncohen73 That's a good change imo, if for no other reason than consistency. +1 from me.

**Pull request merged**
