### PR TITLE
Auto-closes issues on PR merge

### LINKED ISSUE #56: Auto-close issues in PR template
Right now the PR template has `fixes issue #xx`. Perhaps this should be changed to something like `Fixes #xx` so that the issue will be closed automatically when the PR is merged.

### PR DESCRIPTION
**Pull request by subnomo**
Fixes #56 
## Changes in this PR.

- [X] Change `fixes issue #xx` to `Fixes #xx`
## Testing this PR.

1. Create pull request
### Expected Output.

```
Fixes #xx
...
```

@osuosl/devs

### CODE REVIEW

**Comment by ElijahCaine** [comment]
... Why?

**Comment by MaraJade** [comment]
+1

**Comment by pop** [comment]
~~...Why?~~
EDIT: Ah, I see for auto-closing issues. +1 from me.

**Comment by aaroncohen73** [comment]
+1

**Pull request merged**
