### PR TITLE
Bumped Pymesync version to 0.1.6

### LINKED ISSUE #88: Bump Pymesync version to 0.1.6

### PR DESCRIPTION
**Pull request by aaroncohen73**
Fixes #88 
## Changes in this PR.

- [X] Bumped Pymesync version in `requirements.txt` to Pymesync 0.1.7
## Testing this PR.

1. Run `pip install --upgrade -r requirements.txt`
2. Run `nosetests`
### Expected Output.

```
$ nosetests
..................................................................
----------------------------------------------------------------------
Ran 66 tests in 1.559s

OK
```

@osuosl/devs

### CODE REVIEW

**Comment by subnomo** [comment]
Looks good. :+1:

**Comment by pop** [comment]
@aaroncohen73 @Kennric bumped the version to 0.1.7, we should probably stay up-to-date even if it was an unnecessary bump.

Once that's done, this gets a +1 from me.

**Comment by aaroncohen73** [comment]
@ElijahCaine

**Comment by ElijahCaine** [comment]
@aaroncohen73 @Kennric bumped the version to 0.1.7, we should probably stay up-to-date even if it was an unnecessary bump.

Once that's done, this gets a +1 from me.

**Pull request merged**
