### PR TITLE
times summary

### LINKED ISSUE #103: Summaries [5]

### PR DESCRIPTION
**Pull request by leian7**
Fixes #103 
## Changes in this PR.

- [X] Tests for the existence of and the accuracy of the "view times" summary box
- [X] Generates summary data
- [X] Displays summary data in "view times" view
## Testing this PR.

To run tests:
1. `nosetests`

To view in-browser:
1. `docker-compose up`
2. Visit localhost:5000
3. Log in as admin
4. Hit view times, then submit
### Expected Output.

Tests pass.
summary

@aaroncohen73 @kennric @subnomo

### CODE REVIEW

**Comment by aaroncohen73** [comment]
+1

**Comment by Kennric** [comment]
I think it would be easier to read if the summary items names were not centered.

also, the summary does not appear if you just go to /times/ - is it possible to summarize even the default view of all times?
@leian7

**Comment by aaroncohen73** [comment]
@Kennric `/times/` doesn't get times from TimeSync and show them unless the filter form is submitted so that the page doesn't take a long time to initially load (and because pagination doesn't exist in the API yet). Showing the time summary on initial load would require getting all of the times from TimeSync and potentially taking a long time to load like it did before.

**Comment by Kennric** [comment]
@aaroncohen73 I see times when I go to /times/ and haven't submitted. Is there some caching going on, or is it in fact fetching all times?

I think a reasonable compromise would be for the default view to query timesync for the last month or week of times, summarize and display the summary box.

**Comment by leian7** [comment]
@Kennric That wasn't happening before; when you go to times there should just be the times' category headers there. Maybe something happened during my rebase?

**Comment by Kennric** [comment]
@aaroncohen73, @leian7 - can one or both of you try to replicate on this branch?

**Comment by leian7** [comment]
@Kennric Yes, right now when you go to times you can see all the times.

**Comment by Kennric** [comment]
@leian7 in that case, let's add the summary box to the default view - does it behave well if there are no times available?

**Comment by leian7** [comment]
@Kennric Not really. If the `summary` dictionary that's passed to the template is empty, it'll error out if you try to display values that don't exist from it. @aaroncohen73 suggested an if statement so that the summary only displays when there's actually something to display, i.e. after the user submits the form. I don't know why all the times are appearing by default all of a sudden.

**Comment by leian7** [comment]
I think I figured it out

**Comment by leian7** [comment]
Times were being retrieved twice, both if the form was submitted and if it wasn't. I commented the extra lines out and added a note in view_times.py, near the bottom of the file. So now it's back to how it was; is this okay @Kennric ? It actually may be possible to have the summary show up by default if you want that. But like @aaroncohen73 said, it just means you have to get the times upon first page load.

**Comment by Kennric** [comment]
@leian7 I think we do want at least a limited set of times pulled on page load, but we don't need to do that in this PR - I'll review as is, and we can file an issue for that feature later

**Comment by Kennric** [comment]
+1

**Pull request merged**
