### PR TITLE
Added delete time page

### LINKED ISSUE #61: Delete times
Functionality should be added to delete times. This could be done by implementing a new `/times/delete` endpoint that can be accessed from `/times` by selecting times to delete (This would be similar to how time editing is being implemented). Time deletion would be restricted to site admins and the user that the time belongs to.

### PR DESCRIPTION
**Pull request by aaroncohen73**
Fixes #61 
## Changes in this PR.

- [X] Added `delete_time()` view and `/times/delete` endpoint
- [X] Added link to delete time in `view_times()` view
## Testing this PR.

1. Run `nosetests`
2. Log in and submit a time
3. Go to `/times` and click on the **DELETE** link next to the time
4. When asked if you want to delete the time, click yes
5. See that the time has been deleted
### Expected Output.

```
$ nosetests
........................................
----------------------------------------------------------------------
Ran 40 tests in 0.730s

OK
```

@osuosl/devs

### CODE REVIEW

**Comment by pop** [comment]
@aaroncohen73 This code looks good, but in your tests I don't actually see any instance where you delete a time.

**Comment by aaroncohen73** [comment]
@ElijahCaine The tests have been fixed

**Comment by Kennric** [comment]
I don't see a test for deleting a time logged in as a user (only accessing the form). I thought that a user was allowed to delete their own time? @ElijahCaine ?

**Comment by subnomo** [comment]
Needs to be rebased.

**Comment by pop** [comment]
@aaroncohen73 +1 from me, test improvements are good.

**Comment by subnomo** [comment]
Code looks good, does what it should do. :+1:

**Pull request merged**
